[package]

name = "todomvc"
version = "0.1.0"
license = "MIT"
description = "TodoMVC example ported to Rust."
authors = ["Tim Cameron Ryan <tim@timryan.org>"]

[[bin]]
name = "todomvc"

[dependencies]
rustc-serialize = "0.3.1"
handlebars = "0.23.0"
webplatform = "0.4.0"
maplit = "0.1.4"
